In [1]:
import numpy as np


In [26]:
def length_normalize_dimensionwise(
    matrix: np.ndarray,
) -> np.ndarray:


    norms = np.sqrt(np.sum(matrix ** 2, axis=1))
    norms[norms == 0] = 1
    return  matrix / norms[:, np.newaxis]


In [62]:
matrix = np.array([[0.0, -1.0, -1.0],
         [-1.0, -1.0, -1.0],
         [1.0, -1.0, -1.0],
        [0.0, -1.0, 1.0],
        [0.0, 1.0, -1.0],
        [-1.0, -1.0, 1.0],
        [-1.0, 1.0, -1.0],
        [1.0, -1.0, 1.0],
        [1.0, 1.0, -1.0]])

matrix = length_normalize_dimensionwise(matrix)
v = np.array([[0.0,0.01,0.01]])
v = length_normalize_dimensionwise(v)


In [63]:
v

array([[0.        , 0.70710678, 0.70710678]])

In [64]:
matrix

array([[ 0.        , -0.70710678, -0.70710678],
       [-0.57735027, -0.57735027, -0.57735027],
       [ 0.57735027, -0.57735027, -0.57735027],
       [ 0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.70710678, -0.70710678],
       [-0.57735027, -0.57735027,  0.57735027],
       [-0.57735027,  0.57735027, -0.57735027],
       [ 0.57735027, -0.57735027,  0.57735027],
       [ 0.57735027,  0.57735027, -0.57735027]])

In [65]:
int(np.argmax(v.dot(matrix.T)))

3

In [70]:
import torch
v = np.array([0.0,0.90,-0.98])
t = torch.tensor(v)
t.view(-1)
t

tensor([ 0.0000,  0.9000, -0.9800], dtype=torch.float64)

In [71]:
matrix = np.array([[0.0, -1.0, -1.0],
         [-1.0, -1.0, -1.0],
         [1.0, -1.0, -1.0],
        [0.0, -1.0, 1.0],
        [0.0, 1.0, -1.0],
        [-1.0, -1.0, 1.0],
        [-1.0, 1.0, -1.0],
        [1.0, -1.0, 1.0],
        [1.0, 1.0, -1.0]])

v = np.array([0.0,0.01,0.01])

np.argmin(
    np.sum(
        (
            matrix[np.newaxis, :]
            - v[np.newaxis, :][:, np.newaxis]
        )
        ** 2,
        -1,
    )
)


3

In [73]:
torch.argmax(t)

tensor(1)